builders:
  tp_router:
    import: "package:tp_router_generator/builder.dart"
    builder_factories: ["tpRouterBuilder"]
    build_extensions: {"lib/$lib$": ["lib/tp_router.g.dart"]}
    auto_apply: dependents
    build_to: source
    required_inputs: [".dart"]
