// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tp_router_generator

import 'package:tp_router/tp_router.dart';
import 'package:example/pages/home_page.dart';
import 'package:example/pages/main_shell_page.dart';
import 'package:example/pages/settings_page.dart';
import 'package:example/pages/user_page.dart';

class MainShellRoute {
  static final TpStatefulShellRouteInfo routeInfo = TpStatefulShellRouteInfo(
    builder: (context, navigationShell) => MainShellPage(navigationShell: navigationShell),
    branches: [
      [
        HomeRoute.routeInfo,
      ],
      [
        SettingsRoute.routeInfo,
      ],
    ],
  );
}


/// Route class for [UserPage].
///
/// Usage:
/// ```dart
/// UserRoute(id: 123).tp(context);
/// ```
class UserRoute extends BaseRoute {
  final int id;
  final String name;
  final int age;

  const UserRoute({
    required this.id,
    this.name = '',
    this.age = 0,
  });

  /// The route path.
  static const String path = '/user/:id';

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/user/:id',
    name: 'user',
    isInitial: false,
    params: [
      TpParamInfo(
        name: 'id',
        urlName: 'id',
        type: 'int',
        isRequired: true,
        source: 'path',
      ),
      TpParamInfo(
        name: 'name',
        urlName: 'name',
        type: 'String',
        isRequired: false,
        source: 'query',
      ),
      TpParamInfo(
        name: 'age',
        urlName: 'age',
        type: 'int',
        isRequired: false,
        source: 'query',
      ),
    ],
    builder: (settings) {
    final id = (() {
      final raw = settings.pathParams['id'];
      if (raw == null) {
        throw ArgumentError('Missing required parameter: id');
      }
      final parsed = int.tryParse(raw);
      if (parsed == null) {
        throw ArgumentError('Invalid int value for: id');
      }
      return parsed;
    })();
    final name = settings.queryParams['name'];
    final age = (() {
      final raw = settings.queryParams['age'];
      if (raw == null) {
        return null;
      }
      final parsed = int.tryParse(raw);
      if (parsed == null) {
        return null;
      }
      return parsed;
    })();
      return UserPage(id: id, name: name ?? '', age: age ?? 0);
    },
  );

  @override
  String get fullPath {
    var p = '/user/:id';
    p = p.replaceAll(':id', id.toString());
    final queryParts = <String>[];
    queryParts.add('name=${Uri.encodeComponent(name.toString())}');
    queryParts.add('age=${Uri.encodeComponent(age.toString())}');
    if (queryParts.isNotEmpty) p = '$p?${queryParts.join('&')}';
    return p;
  }

}


/// Route class for [HomePage].
///
/// Usage:
/// ```dart
/// HomeRoute().tp(context);
/// ```
class HomeRoute extends BaseRoute {
  const HomeRoute();

  /// The route path.
  static const String path = '/';

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/',
    isInitial: true,
    params: [
    ],
    builder: (settings) {
      return HomePage();
    },
  );

  @override
  String get fullPath {
    var p = '/';
    return p;
  }

}


/// Route class for [SettingsPage].
///
/// Usage:
/// ```dart
/// SettingsRoute().tp(context);
/// ```
class SettingsRoute extends BaseRoute {
  const SettingsRoute();

  /// The route path.
  static const String path = '/settings';

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/settings',
    name: 'settings',
    isInitial: false,
    params: [
    ],
    builder: (settings) {
      return SettingsPage();
    },
  );

  @override
  String get fullPath {
    var p = '/settings';
    return p;
  }

}


/// All generated routes in the application.
///
/// Use this list to initialize [TpRouter]:
/// ```dart
/// final router = TpRouter(routes: tpRoutes);
/// ```
List<TpRouteBase> get tpRoutes => [
  MainShellRoute.routeInfo,
  UserRoute.routeInfo,
];
