// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tp_router_generator

import 'package:tp_router/tp_router.dart';
import 'package:example/pages/details_page.dart';
import 'package:example/pages/home_page.dart';
import 'package:example/pages/main_shell_page.dart';
import 'package:example/pages/settings_page.dart';
import 'package:example/pages/user_page.dart';

/// Route class for [DetailsPage].
///
/// Usage:
/// ```dart
/// DetailsRoute().tp(context);
/// ```
class DetailsRoute extends TpRouteData {
  final String title;
  final int level;

  const DetailsRoute({
    this.title = 'Details',
    this.level = 1,
  });

  /// The route path.
  static const String path = '/details';

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/details',
    isInitial: false,
    params: [
      TpParamInfo(
        name: 'title',
        urlName: 'title',
        type: 'String',
        isRequired: false,
        source: 'extra',
      ),
      TpParamInfo(
        name: 'level',
        urlName: 'level',
        type: 'int',
        isRequired: false,
        source: 'query',
      ),
    ],
    builder: (settings) {
      final title = (() {
        final extraValue = settings.extra['title'];
        if (extraValue is String) {
          return extraValue;
        }
        return settings.pathParams['title'] ??
            settings.queryParams['title'] ??
            null;
      })();
      final level = (() {
        final raw = settings.queryParams['level'];
        if (raw == null) {
          return null;
        }
        final parsed = int.tryParse(raw);
        if (parsed == null) {
          return null;
        }
        return parsed;
      })();
      return DetailsPage(title: title ?? 'Details', level: level ?? 1);
    },
    transition: const TpSlideTransition(),
    transitionDuration: const Duration(microseconds: 500000),
    reverseTransitionDuration: const Duration(microseconds: 300000),
  );

  @override
  String get fullPath {
    var p = '/details';
    final queryParts = <String>[];
    queryParts.add('level=${Uri.encodeComponent(level.toString())}');
    if (queryParts.isNotEmpty) p = '$p?${queryParts.join('&')}';
    return p;
  }

  @override
  Map<String, dynamic> get extra => {
        'title': title,
      };
}

/// Route class for [HomePage].
///
/// Usage:
/// ```dart
/// HomeRoute().tp(context);
/// ```
class HomeRoute extends TpRouteData {
  const HomeRoute();

  /// The route path.
  static const String path = '/';

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/',
    isInitial: true,
    params: [],
    builder: (settings) {
      return HomePage();
    },
  );

  @override
  String get fullPath {
    var p = '/';
    return p;
  }
}

class MainShellRoute {
  static final TpStatefulShellRouteInfo routeInfo = TpStatefulShellRouteInfo(
    builder: (context, navigationShell) =>
        MainShellPage(navigationShell: navigationShell),
    branches: [
      [
        HomeRoute.routeInfo,
      ],
      [
        SettingsRoute.routeInfo,
      ],
    ],
  );
}

/// Route class for [SettingsPage].
///
/// Usage:
/// ```dart
/// SettingsRoute().tp(context);
/// ```
class SettingsRoute extends TpRouteData {
  const SettingsRoute();

  /// The route path.
  static const String path = '/settings';

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/settings',
    name: 'settings',
    isInitial: false,
    params: [],
    builder: (settings) {
      return SettingsPage();
    },
  );

  @override
  String get fullPath {
    var p = '/settings';
    return p;
  }
}

/// Route class for [UserPage].
///
/// Usage:
/// ```dart
/// UserRoute(id: 123).tp(context);
/// ```
class UserRoute extends TpRouteData {
  final int id;
  final String name;
  final int age;

  const UserRoute({
    required this.id,
    this.name = '',
    this.age = 0,
  });

  /// The route path.
  static const String path = '/user/:id';

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/user/:id',
    name: 'user',
    isInitial: false,
    params: [
      TpParamInfo(
        name: 'id',
        urlName: 'id',
        type: 'int',
        isRequired: true,
        source: 'path',
      ),
      TpParamInfo(
        name: 'name',
        urlName: 'name',
        type: 'String',
        isRequired: false,
        source: 'query',
      ),
      TpParamInfo(
        name: 'age',
        urlName: 'age',
        type: 'int',
        isRequired: false,
        source: 'query',
      ),
    ],
    builder: (settings) {
      final id = (() {
        final raw = settings.pathParams['id'];
        if (raw == null) {
          throw ArgumentError('Missing required parameter: id');
        }
        final parsed = int.tryParse(raw);
        if (parsed == null) {
          throw ArgumentError('Invalid int value for: id');
        }
        return parsed;
      })();
      final name = settings.queryParams['name'];
      final age = (() {
        final raw = settings.queryParams['age'];
        if (raw == null) {
          return null;
        }
        final parsed = int.tryParse(raw);
        if (parsed == null) {
          return null;
        }
        return parsed;
      })();
      return UserPage(id: id, name: name ?? '', age: age ?? 0);
    },
  );

  @override
  String get fullPath {
    var p = '/user/:id';
    p = p.replaceAll(':id', id.toString());
    final queryParts = <String>[];
    queryParts.add('name=${Uri.encodeComponent(name.toString())}');
    queryParts.add('age=${Uri.encodeComponent(age.toString())}');
    if (queryParts.isNotEmpty) p = '$p?${queryParts.join('&')}';
    return p;
  }
}

/// All generated routes in the application.
///
/// Use this list to initialize [TpRouter]:
/// ```dart
/// final router = TpRouter(routes: tpRoutes);
/// ```
List<TpRouteBase> get tpRoutes => [
      DetailsRoute.routeInfo,
      MainShellRoute.routeInfo,
      UserRoute.routeInfo,
    ];
