import 'package:flutter/widgets.dart';
import 'package:teleport_router/teleport_router.dart';

/// The prefix used for teleport_router managed route names.
///
/// All routes generated by teleport_router will have names starting with this prefix.
/// This is used by [TeleportRouteObserver] to identify and track teleport_router routes.
const String kTeleportRoutePrefix = 'teleport_router_';

/// Mixin for [NavigatorObserver]s that contain child observers.
///
/// Implement this on composite observer classes so that
/// [TeleportRouter] can search nested observers for [TeleportRouteObserver].
mixin TeleportCompositeObserver on NavigatorObserver {
  /// The child observers contained within this composite observer.
  List<NavigatorObserver> get observers;
}

/// Navigator observer that tracks route history for stack manipulation.
///
/// This observer maintains a mapping of route names to Route instances,
/// allowing `removeRoute()` and `removeWhere()` methods to remove specific routes from the stack.
class TeleportRouteObserver extends NavigatorObserver {
  /// Map of route name to lists of Route instances (one name can map to multiple route instances)
  final Map<String, List<Route>> _routesByName = {};

  /// All routes in order (bottom to top)
  final List<Route> _allRoutes = [];

  /// Actual TeleportRouteData instances for each route
  final Map<Route, TeleportRouteData> _routeDataMap = {};

  /// Routes marked for removal when they become active.
  final Set<Route> _pendingRemovals = {};

  /// The navigator state currently observed.
  NavigatorState? _currentNavigator;

  /// Clear all tracked routes.
  @visibleForTesting
  void clear() {
    _routesByName.clear();
    _allRoutes.clear();
    _routeDataMap.clear();
    _pendingRemovals.clear();
  }

  /// Mark a route to be removed automatically when it becomes active (is popped to).
  void markRouteForRemoval(Route route) {
    _pendingRemovals.add(route);
  }

  /// Check if a route should be tracked by this observer.
  ///
  /// Routes are tracked when they preserve [TeleportRouteData] in
  /// [RouteSettings.arguments], or when they use a generated route name.
  bool _shouldTrackRoute(Route route) {
    if (route.settings.arguments is TeleportRouteData) {
      return true;
    }
    final name = route.settings.name;
    return name != null && name.startsWith(kTeleportRoutePrefix);
  }

  @override
  void didPush(Route route, Route? previousRoute) {
    // Check if the navigator instance has changed (e.g., widget rebuild).
    // If so, clear old state to prevent memory leaks and invalid references.
    if (navigator != _currentNavigator) {
      clear();
      _currentNavigator = navigator;
    }

    if (_shouldTrackRoute(route)) {
      _allRoutes.add(route);
      _addRouteToMap(route);
      _tryExtractRouteData(route);
    }
  }

  @override
  void didPop(Route route, Route? previousRoute) {
    if (_shouldTrackRoute(route)) {
      _allRoutes.remove(route);
      _removeRouteFromMap(route);
      _routeDataMap.remove(route);
    }
    _pendingRemovals.remove(route); // Cleanup if popped normally

    _schedulePendingRemovalIfNeeded();
  }

  @override
  void didRemove(Route route, Route? previousRoute) {
    if (_shouldTrackRoute(route)) {
      _allRoutes.remove(route);
      _removeRouteFromMap(route);
      _routeDataMap.remove(route);
    }
    _pendingRemovals.remove(route);
    _schedulePendingRemovalIfNeeded();
  }

  @override
  void didReplace({Route? newRoute, Route? oldRoute}) {
    int index = -1;
    if (oldRoute != null && _shouldTrackRoute(oldRoute)) {
      index = _allRoutes.indexOf(oldRoute);
      if (index != -1) {
        _allRoutes.removeAt(index);
      }
      _removeRouteFromMap(oldRoute);
      _routeDataMap.remove(oldRoute);
      _pendingRemovals.remove(oldRoute);
    }
    if (newRoute != null && _shouldTrackRoute(newRoute)) {
      if (index != -1) {
        _allRoutes.insert(index, newRoute);
      } else {
        _allRoutes.add(newRoute);
      }
      _addRouteToMap(newRoute);
      _tryExtractRouteData(newRoute);
    }
  }

  /// Find route by name (returns first match)
  Route? findRoute(String name) {
    final routes = _routesByName[name];
    return routes?.isNotEmpty == true ? routes!.first : null;
  }

  /// Find all routes matching the name
  List<Route> findAllRoutes(String name) {
    return _routesByName[name]?.toList() ?? [];
  }

  /// Get all routes in the stack
  List<Route> get allRoutes => List.unmodifiable(_allRoutes);

  /// Get TeleportRouteData for a specific route
  ///
  /// Returns the stored TeleportRouteData if available, otherwise tries to
  /// extract from route.settings.arguments as TeleportRouteData.
  TeleportRouteData? getRouteData(Route route) {
    // Try cached data first
    if (_routeDataMap.containsKey(route)) {
      return _routeDataMap[route];
    }

    // Try to extract from arguments
    final arguments = route.settings.arguments;
    if (arguments is TeleportRouteData) {
      _routeDataMap[route] = arguments;
      return arguments;
    }

    return null;
  }

  /// Get all route data entries, ordered by stack position (bottom to top).
  Map<Route, TeleportRouteData> get allRouteData {
    final sortedMap = <Route, TeleportRouteData>{};
    for (final route in _allRoutes) {
      if (_routeDataMap.containsKey(route)) {
        sortedMap[route] = _routeDataMap[route]!;
      }
    }
    return Map.unmodifiable(sortedMap);
  }

  void _addRouteToMap(Route route) {
    final name = _trackedRouteName(route);
    if (name != null) {
      _routesByName.putIfAbsent(name, () => []).add(route);
    }
  }

  void _removeRouteFromMap(Route route) {
    final name = _trackedRouteName(route);
    if (name != null) {
      _routesByName[name]?.remove(route);
      if (_routesByName[name]?.isEmpty == true) {
        _routesByName.remove(name);
      }
    }
  }

  /// Extract and cache TeleportRouteData from the route.
  void _tryExtractRouteData(Route route) {
    _routeDataMap[route] = TeleportRouteData.fromRoute(route);
  }

  String? _trackedRouteName(Route route) {
    final arguments = route.settings.arguments;
    if (arguments is TeleportRouteData && arguments.routeName != null) {
      return arguments.routeName;
    }
    return route.settings.name;
  }

  void _schedulePendingRemovalIfNeeded() {
    if (_pendingRemovals.isEmpty || _allRoutes.isEmpty) {
      return;
    }

    final topTrackedRoute = _allRoutes.last;
    if (!_pendingRemovals.contains(topTrackedRoute)) {
      return;
    }

    // Keep peeling overlays until the highest tracked pending route is gone.
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final currentNavigator = navigator;
      if (currentNavigator == null || !currentNavigator.canPop()) return;

      // Re-verify the top route is still pending removal (stack may have changed).
      if (_allRoutes.isEmpty || !_pendingRemovals.contains(_allRoutes.last)) {
        return;
      }

      currentNavigator.pop();
      WidgetsBinding.instance.scheduleFrame();
    });
  }
}
